name: Compile React/JSX source plain JS
on: [push]
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '14'
        - run: npm install
        - run: npm run build
        - name: Commit files
           git update-index --refresh | wc -l
           if: ${{ (git update-index --refresh | wc -l) > 0 }}
          run: |
            git config --local user.email "github-actions@users.noreply.github.com"
            git config --local user.name "github-actions"
            git commit -m "Add changes" -a

